import Sidebar from "./Sidebar";
import type { Metadata } from "next";
import { AuthProvider } from "./AuthProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="absolute">
          <AuthProvider>
            <Sidebar />
          </AuthProvider>
        </div>
        <div className="flex justify-center">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
